/**
 * DSE 本地离线数据集预设清单（仅免费公开数据集）
 * 🔥 在线时优先使用服务端列表（home-web/server/src/routes/datasets.ts，支持付费/上下架）；
 *    本文件仅在服务端不可达时兜底，因此只放免费条目——付费数据集（如 A股十年数据）只存在于服务端，
 *    离线回退不能免费拿到，否则绕过计费。
 * 直链格式 /datasets/{namespace}/{name}/resolve/master/{file} 匿名可下；
 * 文件名均已实测核对；新增条目请先验证直链有效（curl -r 0-100 看 206/302）。
 */

export interface PresetDataset {
  id: string;
  /** 中文名（zh 语言显示） */
  nameZh: string;
  /** 英文名（en 语言显示） */
  nameEn: string;
  descZh: string;
  descEn: string;
  /** pretrain=预训练语料 sft=指令微调 domain=领域数据（金融/医疗/蛋白质等） */
  category: 'pretrain' | 'sft' | 'domain';
  fileName: string;
  url: string;
  /** 展示用近似大小（字节） */
  sizeBytes: number;
}

export const PRESET_DATASETS: PresetDataset[] = [
  {
    id: 'tinystories-train',
    nameZh: 'TinyStories 训练集',
    nameEn: 'TinyStories (train)',
    descZh: 'GPT 生成的英文小故事，词汇量小，语言模型入门首选',
    descEn: 'Synthetic English stories with small vocabulary, best for LM beginners',
    category: 'pretrain',
    fileName: 'TinyStories-train.txt',
    url: 'https://modelscope.cn/datasets/AI-ModelScope/TinyStories/resolve/master/TinyStories-train.txt',
    sizeBytes: 1_100_000_000,
  },
  {
    id: 'tinystories-v2',
    nameZh: 'TinyStories V2 (GPT-4)',
    nameEn: 'TinyStories V2 (GPT-4)',
    descZh: 'GPT-4 生成的更高质量版本，训练效果更好',
    descEn: 'Higher-quality version generated by GPT-4',
    category: 'pretrain',
    fileName: 'TinyStoriesV2-GPT4-train.txt',
    url: 'https://modelscope.cn/datasets/AI-ModelScope/TinyStories/resolve/master/TinyStoriesV2-GPT4-train.txt',
    sizeBytes: 2_200_000_000,
  },
  {
    id: 'tinystories-valid',
    nameZh: 'TinyStories 验证集',
    nameEn: 'TinyStories (valid)',
    descZh: '验证损失用的小验证集，配套训练集使用',
    descEn: 'Small validation set for loss evaluation',
    category: 'pretrain',
    fileName: 'tinystories-valid.txt',
    url: 'https://modelscope.cn/datasets/AI-ModelScope/TinyStories/resolve/master/tinystories-valid.txt',
    sizeBytes: 22_000_000,
  },
  {
    id: 'alpaca-gpt4-zh',
    nameZh: 'Alpaca GPT4 中文指令集',
    nameEn: 'Alpaca GPT4 (zh)',
    descZh: 'GPT-4 生成的中文指令数据，指令微调（SFT）入门',
    descEn: 'GPT-4 generated Chinese instructions for SFT',
    category: 'sft',
    fileName: 'alpaca_gpt4_data_zh.json',
    url: 'https://modelscope.cn/datasets/AI-ModelScope/alpaca-gpt4-data-zh/resolve/master/alpaca_gpt4_data_zh.json',
    sizeBytes: 48_000_000,
  },
  {
    id: 'alpaca-gpt4-en',
    nameZh: 'Alpaca GPT4 英文指令集',
    nameEn: 'Alpaca GPT4 (en)',
    descZh: 'GPT-4 生成的英文指令数据，与中文版配套使用',
    descEn: 'GPT-4 generated English instructions for SFT',
    category: 'sft',
    fileName: 'alpaca_gpt4_data_en.json',
    url: 'https://modelscope.cn/datasets/AI-ModelScope/alpaca-gpt4-data-en/resolve/master/alpaca_gpt4_data_en.json',
    sizeBytes: 37_000_000,
  },
  {
    id: 'tiny-shakespeare',
    nameZh: 'Tiny Shakespeare',
    nameEn: 'Tiny Shakespeare',
    descZh: '约 1MB 莎士比亚文本，NanoGPT 官方入门数据集，几分钟即可训练一个字符级小语言模型',
    descEn: '~1MB Shakespeare text, NanoGPT starter dataset for a char-level LM in minutes',
    category: 'pretrain',
    fileName: 'input.txt',
    url: 'https://cdn.jsdelivr.net/gh/karpathy/char-rnn@master/data/tinyshakespeare/input.txt',
    sizeBytes: 1_115_394,
  },
  {
    id: 'fineweb-edu-10bt',
    nameZh: 'FineWeb-Edu 样本分片',
    nameEn: 'FineWeb-Edu (10BT sample shard)',
    descZh: '高质量网页教育语料 10BT 样本的首个分片（约 2.1GB parquet），可训练较大语言模型',
    descEn: 'First shard (~2.1GB parquet) of the 10BT sample of high-quality educational web corpus',
    category: 'pretrain',
    fileName: '000_00000.parquet',
    url: 'https://modelscope.cn/datasets/AI-ModelScope/fineweb-edu/resolve/master/sample/10BT/000_00000.parquet',
    sizeBytes: 2_152_819_114,
  },
  {
    id: 'cmb-medical',
    nameZh: 'CMB 中文医疗数据集',
    nameEn: 'CMB (Chinese Medical Benchmark)',
    descZh: '覆盖医学考试与临床问答的中文医疗数据（约 30MB），医疗方向微调/评测可用',
    descEn: 'Chinese medical exam & clinical QA data (~30MB) for medical fine-tuning/evaluation',
    category: 'domain',
    fileName: 'CMB-datasets.zip',
    url: 'https://modelscope.cn/datasets/FreedomIntelligence/CMB/resolve/master/CMB-datasets.zip',
    sizeBytes: 30_079_706,
  },
  {
    id: 'pdb-seqres',
    nameZh: 'PDB 蛋白质序列库',
    nameEn: 'PDB Protein Sequences (seqres)',
    descZh: '全部实验解析蛋白质结构对应的氨基酸序列（约 390MB FASTA），蛋白质语言模型训练数据',
    descEn: 'Amino-acid sequences of all PDB entries (~390MB FASTA), for protein language models',
    category: 'domain',
    fileName: 'pdb_seqres.txt',
    url: 'https://files.wwpdb.org/pub/pdb/derived_data/pdb_seqres.txt',
    sizeBytes: 406_522_395,
  },
  {
    id: 'coco8',
    nameZh: 'COCO8 迷你检测集',
    nameEn: 'COCO8 Mini Detection Set',
    descZh: 'COCO 前 8 张图（4 训练 4 验证）+ 80 类标注（约 433KB zip），YOLO 目标检测分钟级跑通首选',
    descEn: 'First 8 COCO images (4 train / 4 val) with 80-class labels (~433KB zip), quickest way to verify YOLO training',
    category: 'domain',
    fileName: 'coco8.zip',
    url: 'https://github.com/ultralytics/assets/releases/download/v0.0.0/coco8.zip',
    sizeBytes: 443_158,
  },
  {
    id: 'visdrone-train',
    nameZh: 'VisDrone2019 无人机检测·训练集',
    nameEn: 'VisDrone2019-DET (train)',
    descZh: '天津大学无人机航拍检测基准，6471 张图 / 10 类（约 1.4GB zip），YOLO 小目标检测实战数据',
    descEn: 'Tianjin Univ. drone-view detection benchmark, 6471 images / 10 classes (~1.4GB zip) for small-object YOLO training',
    category: 'domain',
    fileName: 'VisDrone2019-DET-train.zip',
    url: 'https://github.com/ultralytics/assets/releases/download/v0.0.0/VisDrone2019-DET-train.zip',
    sizeBytes: 1_549_875_511,
  },
  {
    id: 'visdrone-val',
    nameZh: 'VisDrone2019 无人机检测·验证集',
    nameEn: 'VisDrone2019-DET (val)',
    descZh: 'VisDrone2019-DET 验证集，548 张图（约 78MB zip），配合训练集做 mAP 评估',
    descEn: 'VisDrone2019-DET validation split, 548 images (~78MB zip) for mAP evaluation with the train split',
    category: 'domain',
    fileName: 'VisDrone2019-DET-val.zip',
    url: 'https://github.com/ultralytics/assets/releases/download/v0.0.0/VisDrone2019-DET-val.zip',
    sizeBytes: 81_638_851,
  },
  {
    id: 'visdrone-test',
    nameZh: 'VisDrone2019 无人机检测·测试集',
    nameEn: 'VisDrone2019-DET (test-dev)',
    descZh: 'VisDrone2019-DET 测试集，1610 张图（约 297MB zip），训练完成后做最终评测',
    descEn: 'VisDrone2019-DET test-dev split, 1610 images (~297MB zip) for final evaluation',
    category: 'domain',
    fileName: 'VisDrone2019-DET-test-dev.zip',
    url: 'https://github.com/ultralytics/assets/releases/download/v0.0.0/VisDrone2019-DET-test-dev.zip',
    sizeBytes: 311_251_787,
  },
];
